import json
from pathlib import Path

import networkx as nx
import pandas as pd
import pytest

from dram_viz.definitions import (
    DBSETS_COL,
    ETC_MODULE_DF_TAG,
    FILES_NAMES,
    FUNCTION_HEATMAP_FORM_TAG,
    HEATMAP_MODULES,
    MODULE_STEPS_FORM_TAG,
)
from dram_viz.processing.process_annotations import (
    build_module_net,
    get_annotation_ids_by_row,
)


@pytest.fixture()
def annotations():
    return pd.DataFrame(
        [["genome", "K00001"], ["genome", pd.np.NaN]],
        index=["genome_scaffold_1_1", "genome_scaffold_1_2"],
        columns=["fasta", "ko_id"],
    )


@pytest.fixture()
def genome_summary_frame():
    return pd.DataFrame(
        pd.DataFrame(
            [
                ["K00001", "description", "module1", "main", "header1", "subheader1"],
                ["K12345", "description2", "module2", "main", "header1", "subheader1"],
            ],
            columns=["gene_id", "gene_description", "module", "sheet", "header", "subheader"],
        )
    )


@pytest.fixture()
def summarized_genomes():
    return pd.DataFrame(
        [
            ["K00001", "description", "module1", "main", "header1", "subheader1", 1],
            ["K12345", "description2", "module2", "main", "header1", "subheader1", 0],
        ],
        columns=["gene_id", "gene_description", "module", "sheet", "header", "subheader", "genome"],
    )


@pytest.fixture()
def test_module_nets():
    module_steps_form = pd.read_csv(FILES_NAMES[MODULE_STEPS_FORM_TAG], sep="\t")
    # make module coverage frame
    module_nets = {
        module: build_module_net(module_df)
        for module, module_df in module_steps_form.groupby("module")
        if module in HEATMAP_MODULES
    }
    return module_nets


@pytest.fixture()
def test_module_net(test_module_nets):
    return test_module_nets[HEATMAP_MODULES[0]]


@pytest.fixture()
def test_annotations_df():
    return pd.DataFrame(
        [
            ["", "scaffold_1", "d__Something;p__Another;c__;o__;f__;g__;s__"],
            ["K00844", "scaffold_1", "d__More;p__Test;c__Data;o__;f__;g__;s__"],
            ["K00845", "scaffold_1", "d__Final;p__Test;c__Testing;o__Data;f__;g__;s__"],
        ],
        index=["gene_1", "gene_2", "gene_3"],
        columns=["ko_id", "scaffold", "taxonomy"],
    )


@pytest.fixture()
def test_annotations_ids_by_row_df(test_annotations_df):
    db_id_sets: pd.Series = get_annotation_ids_by_row(test_annotations_df)
    test_annotation_ids_by_row = test_annotations_df.copy()
    test_annotation_ids_by_row[DBSETS_COL] = db_id_sets
    return test_annotation_ids_by_row


@pytest.fixture()
def module_coverage_frame():
    return pd.DataFrame(
        [
            [
                "scaffold_1",
                "M00001",
                "Glycolysis (Embden-Meyerhof pathway), glucose => pyruvate",
                9,
                1,
                1 / 9,
                2,
                "K00844,K00845",
                "gene_2,gene_3",
            ]
        ],
        columns=[
            "genome",
            "module",
            "module_name",
            "steps",
            "steps_present",
            "step_coverage",
            "ko_count",
            "kos_present",
            "genes_present",
        ],
    )


@pytest.fixture()
def module_network():
    network = nx.DiGraph()
    network.add_edges_from(
        [
            ("start", "K00001"),
            ("K00001", "K00002"),
            ("K00001", "K00003"),
            ("K00002", "K00004"),
            ("K00003", "K00013"),
            ("K00013", "K00004"),
        ]
    )
    return network


@pytest.fixture()
def etc_module_df():
    return pd.read_csv(FILES_NAMES[ETC_MODULE_DF_TAG], sep="\t")


@pytest.fixture()
def etc_coverage_df():
    return pd.DataFrame(
        [
            [
                "M00144",
                "NADH:quinone oxidoreductase, prokaryotes",
                "I",
                "scaffold_1",
                14,
                0,
                0.0,
                "",
                "K00330,K00331,K00332,K00333,K00334,K00335,K00336,K00337,K00338,K00339,K00340,K00341,K00342,K00343",
                "Complex I: NADH:quinone oxidoreductase, prokaryotes",
            ],
            [
                "M00145",
                "NAD(P)H:quinone oxidoreductase, chloroplasts and cyanobacteria",
                "I",
                "scaffold_1",
                11,
                0,
                0.0,
                "",
                "K05572,K05573,K05574,K05575,K05576,K05577,K05578,K05579,K05580,K05581,K05582",
                "Complex I: NAD(P)H:quinone oxidoreductase, chloroplasts and cyanobacteria",
            ],
            [
                "M00146",
                "NADH dehydrogenase (ubiquinone) 1 alpha subcomplex",
                "I",
                "scaffold_1",
                14,
                0,
                0.0,
                "",
                "K03945,K03946,K03947,K03948,K03949,K03950,K03951,K03952,K03953,K03954,K03955,K03956,K11352,K11353",
                "Complex I: NADH dehydrogenase (ubiquinone) 1 alpha subcomplex",
            ],
            [
                "M00148",
                "Succinate dehydrogenase (ubiquinone)",
                "II",
                "scaffold_1",
                4,
                0,
                0.0,
                "",
                "K00234,K00235,K00236,K00237",
                "Complex II: Succinate dehydrogenase (ubiquinone)",
            ],
            [
                "M00149",
                "Succinate dehydrogenase, prokaryotes",
                "II",
                "scaffold_1",
                4,
                0,
                0.0,
                "",
                "K00239,K00240,K00241,K00242",
                "Complex II: Succinate dehydrogenase, prokaryotes",
            ],
            [
                "M00150",
                "Fumarate reductase, prokaryotes",
                "II",
                "scaffold_1",
                4,
                0,
                0.0,
                "",
                "K00244,K00245,K00246,K00247",
                "Complex II: Fumarate reductase, prokaryotes",
            ],
            [
                "M00151",
                "Cytochrome bc1 complex respiratory unit",
                "III",
                "scaffold_1",
                3,
                0,
                0.0,
                "",
                "K00411,K00412,K00413",
                "Complex III: Cytochrome bc1 complex respiratory unit",
            ],
            [
                "M00152",
                "Cytochrome bc1 complex",
                "III",
                "scaffold_1",
                10,
                0,
                0.0,
                "",
                "K00411,K00412,K00413,K00414,K00415,K00416,K00417,K00418,K00419,K00420",
                "Complex III: Cytochrome bc1 complex",
            ],
            [
                "M00153",
                "Cytochrome bd ubiquinol oxidase",
                "III",
                "scaffold_1",
                3,
                0,
                0.0,
                "",
                "K00424,K00425,K00426",
                "Complex III: Cytochrome bd ubiquinol oxidase",
            ],
            [
                "M00153",
                "Cytochrome bd ubiquinol oxidase",
                "IV H",
                "scaffold_1",
                3,
                0,
                0.0,
                "",
                "K00424,K00425,K00426",
                "Complex IV H: Cytochrome bd ubiquinol oxidase",
            ],
            [
                "M00156",
                "Cytochrome c oxidase, cbb3-type",
                "IV H",
                "scaffold_1",
                4,
                0,
                0.0,
                "",
                "K00404,K00405,K00406,K00407",
                "Complex IV H: Cytochrome c oxidase, cbb3-type",
            ],
            [
                "M00154",
                "Cytochrome c oxidase",
                "IV L",
                "scaffold_1",
                15,
                0,
                0.0,
                "",
                "K02256,K02257,K02258,K02259,K02260,K02261,K02262,K02263,K02264,K02265,K02266,K02267,K02268,K02269,K02272",
                "Complex IV L: Cytochrome c oxidase",
            ],
            [
                "M00155",
                "Cytochrome c oxidase, prokaryotes",
                "IV L",
                "scaffold_1",
                3,
                0,
                0.0,
                "",
                "K02274,K02275,K02276",
                "Complex IV L: Cytochrome c oxidase, prokaryotes",
            ],
            [
                "M00416",
                "Cytochrome aa3-600 menaquinol oxidase",
                "IV L",
                "scaffold_1",
                4,
                0,
                0.0,
                "",
                "K02826,K02827,K02828,K02829",
                "Complex IV L: Cytochrome aa3-600 menaquinol oxidase",
            ],
            [
                "M00417",
                "Cytochrome o ubiquinol oxidase",
                "IV L",
                "scaffold_1",
                4,
                0,
                0.0,
                "",
                "K02297,K02298,K02299,K02300",
                "Complex IV L: Cytochrome o ubiquinol oxidase",
            ],
            [
                "M00157",
                "F-type ATPase, prokaryotes and chloroplasts",
                "V",
                "scaffold_1",
                8,
                0,
                0.0,
                "",
                "K02108,K02109,K02110,K02111,K02112,K02113,K02114,K02115",
                "Complex V: F-type ATPase, prokaryotes and chloroplasts",
            ],
            [
                "M00158",
                "F-type ATPase, eukaryotes",
                "V",
                "scaffold_1",
                15,
                0,
                0.0,
                "",
                "K02125,K02126,K02127,K02128,K02129,K02130,K02132,K02133,K02134,K02135,K02136,K02137,K02138,K02140,K02141",
                "Complex V: F-type ATPase, eukaryotes",
            ],
            [
                "M00159",
                "V/A-type ATPase, prokaryotes",
                "V",
                "scaffold_1",
                9,
                0,
                0.0,
                "",
                "K02107,K02117,K02118,K02119,K02120,K02121,K02122,K02123,K02124",
                "Complex V: V/A-type ATPase, prokaryotes",
            ],
            [
                "M00160",
                "V-type ATPase, eukaryotes",
                "V",
                "scaffold_1",
                13,
                0,
                0.0,
                "",
                "K02144,K02145,K02146,K02147,K02148,K02149,K02150,K02151,K02152,K02153,K02154,K03661,K03662",
                "Complex V: V-type ATPase, eukaryotes",
            ],
        ],
        columns=[
            "module_id",
            "module_name",
            "complex",
            "genome",
            "path_length",
            "path_length_coverage",
            "percent_coverage",
            "genes",
            "missing_genes",
            "complex_module_name",
        ],
    )


@pytest.fixture()
def function_heatmap_form():
    return pd.read_csv(FILES_NAMES[FUNCTION_HEATMAP_FORM_TAG], sep="\t")


@pytest.fixture()
def functional_df():
    return pd.DataFrame(
        [
            [
                "Photo",
                "Photosynthesis",
                "Photosystem I",
                "",
                "psaA-F; photosystem I P700 chlorophyll a apoprotein A1",
                "",
                "scaffold_1",
                False,
                "Photo: Photosystem I",
            ],
            [
                "Photo",
                "Photosynthesis",
                "Photosystem II",
                "",
                "psbA, psbD photosystem II reaction center D1 protein [EC:1.10.3.9]",
                "fhs (formyltetrahydrofolate (THF) synthetase)",
                "scaffold_1",
                False,
                "Photo: Photosystem II",
            ],
            [
                "Nitrogen",
                "Nitrification",
                "ammonia => nitrite",
                "",
                "ammonia monooxygenase [EC:1.14.99.39] [RN:R00148]",
                "",
                "scaffold_1",
                False,
                "Nitrogen: ammonia => nitrite",
            ],
            [
                "Nitrogen",
                "Nitrification",
                "Bacterial/Archaeal ammonia oxidation",
                "",
                "amoA; Methane/ammonia monooxygenase subunit A (aka: particulate ammonia monooxygenase) [EC:1.14.99.39] [RN:R00148]",
                "amoA",
                "scaffold_1",
                False,
                "Nitrogen: Bacterial/Archaeal ammonia oxidation",
            ],
            [
                "Nitrogen",
                "Nitrification",
                "Bacterial (aerobic-specific) ammonia oxidation",
                "",
                "hao: Hydroxylamine dehydrogenase [EC:1.7.2.6] [RN:R10164]",
                "hao",
                "scaffold_1",
                False,
                "Nitrogen: Bacterial (aerobic-specific) ammonia oxidation",
            ],
            [
                "Nitrogen",
                "Nitrification",
                "Bacterial (anaerobic-specific) ammonia oxidation",
                "",
                "hzs; Hydrazine synthase subunit (aka: hzsC) [EC:1.7.2.7] [RN:R09799]",
                "hzs",
                "scaffold_1",
                False,
                "Nitrogen: Bacterial (anaerobic-specific) ammonia oxidation",
            ],
            [
                "Nitrogen",
                "Nitrification",
                "nitrite=> nitrate",
                "",
                "nxrA; Nitrite oxidoreductase, alpha subunit [EC:1.7.99.-] [RN:R00978]; nxrB; Nitrite oxidoreductase, beta subunit [EC:1.7.99.-] [RN:R00978]",
                "",
                "scaffold_1",
                False,
                "Nitrogen: nitrite=> nitrate",
            ],
            [
                "Nitrogen",
                "Denitrification",
                "nitrate => nitrite",
                "",
                "periplasmic nitrate reductase NapA [EC:1.7.99.-] [RN:R00798] or nitrate reductase 1 NarG [EC:1.7.99.-] [RN:R00798]",
                "",
                "scaffold_1",
                False,
                "Nitrogen: nitrate => nitrite",
            ],
            [
                "Nitrogen",
                "Denitrification",
                "nitrite => nitric oxide",
                "",
                "respiratory nitrite reductase [EC:1.7.1.15] [RN:R00787]",
                "",
                "scaffold_1",
                False,
                "Nitrogen: nitrite => nitric oxide",
            ],
            [
                "Nitrogen",
                "Denitrification",
                "Dissimilatory nitrite reduction to ammonia (DNRA)",
                "",
                "nrfA; Nitrite reductase (cytochrome c-552) [EC:1.7.2.2] [RN:R05712]; nrfH; cytochrome c nitrite reductase small subunit [EC:1.7.2.2] [RN:R05712]",
                "nrfA",
                "scaffold_1",
                False,
                "Nitrogen: Dissimilatory nitrite reduction to ammonia (DNRA)",
            ],
            [
                "Nitrogen",
                "Denitrification",
                "nitric oxide => nitrous oxide",
                "",
                "nitric oxide reductase [EC:1.7.2.5] [RN:R00294]",
                "",
                "scaffold_1",
                False,
                "Nitrogen: nitric oxide => nitrous oxide",
            ],
            [
                "Nitrogen",
                "Denitrification",
                "nitrous oxide => nitrogen",
                "",
                "nitrous-oxide reductase [EC:1.7.2.4] [RN:R02804]",
                "",
                "scaffold_1",
                False,
                "Nitrogen: nitrous oxide => nitrogen",
            ],
            [
                "Nitrogen",
                "Nitrogen fixation",
                "nitrogen => ammonia",
                "",
                "nitrogenase iron protein [RN:R05185]",
                "",
                "scaffold_1",
                False,
                "Nitrogen: nitrogen => ammonia",
            ],
            [
                "Nitrogen",
                "Nitrogen fixation",
                "Nitrogen fixation altennative",
                "",
                "vnfD; Vanadium-dependent nitrogenase alpha chain [EC:1.18.6.2] [RN:R12084]",
                "vnfH",
                "scaffold_1",
                False,
                "Nitrogen: Nitrogen fixation altennative",
            ],
            [
                "Sulfur",
                "Sulfur metabolism",
                "dissimilatory sulfate reduction (and oxidation) sulfate => sulfide",
                "",
                "dissimilatory sulfite reductase alpha subunit [EC:1.8.99.5]",
                "dsrA or dsrB",
                "scaffold_1",
                False,
                "Sulfur: dissimilatory sulfate reduction (and oxidation) sulfate => sulfide",
            ],
            [
                "Sulfur",
                "Sulfur metabolism",
                "thiosulfate => sulfite",
                "",
                "thiosulfate reductase / polysulfide reductase chain A [EC:1.8.5.5]",
                "phsA, psrA",
                "scaffold_1",
                False,
                "Sulfur: thiosulfate => sulfite",
            ],
            [
                "Sulfur",
                "Sulfur metabolism",
                "Thiosulfate oxidation by SOX complex, thiosulfate => sulfate",
                "",
                "",
                "",
                "scaffold_1",
                False,
                "Sulfur: Thiosulfate oxidation by SOX complex, thiosulfate => sulfate",
            ],
            [
                "Sulfur",
                "Sulfur metabolism",
                "tetrathionate => thiosulfate",
                "",
                "",
                "ttrA",
                "scaffold_1",
                False,
                "Sulfur: tetrathionate => thiosulfate",
            ],
            [
                "Other",
                "Reductases and Electron transport chain components",
                "selenate/Chlorate reduction",
                "",
                "selenate/chlorate reductase subunit alpha",
                "",
                "scaffold_1",
                False,
                "Other: selenate/Chlorate reduction",
            ],
            [
                "Other",
                "Reductases and Electron transport chain components",
                "TMAO reductase",
                "",
                "trimethylamine-N-oxide reductase (cytochrome c) [EC:1.7.2.3]",
                "",
                "scaffold_1",
                False,
                "Other: TMAO reductase",
            ],
            [
                "Other",
                "Reductases and Electron transport chain components",
                "mercury reduction",
                "",
                "mercury(II) reductase",
                "",
                "scaffold_1",
                False,
                "Other: mercury reduction",
            ],
            [
                "Other",
                "Reductases and Electron transport chain components",
                "arsenate reduction, pt 1",
                "",
                "arsenate reductase (glutaredoxin); ArsC (ambiguous)",
                "",
                "scaffold_1",
                False,
                "Other: arsenate reduction, pt 1",
            ],
            [
                "Other",
                "Reductases and Electron transport chain components",
                "arsenate reduction, pt 2",
                "",
                "arsenate reductase (donor); arsenate:(acceptor) oxidoreductase",
                "",
                "scaffold_1",
                False,
                "Other: arsenate reduction, pt 2",
            ],
            [
                "C1 metabolism",
                "Methanogenesis and methanotrophy",
                "Key functional gene",
                "",
                "methyl-coenzyme M reductase [EC:2.8.4.1] [RN:R04541]",
                "mcrA",
                "scaffold_1",
                False,
                "C1 metabolism: Key functional gene",
            ],
            [
                "C1 metabolism",
                "Methanogenesis and methanotrophy",
                "acetate => methane, pt 1",
                "",
                "acetyl-CoA synthetase [EC:6.2.1.1] [RN:R00235]",
                "",
                "scaffold_1",
                False,
                "C1 metabolism: acetate => methane, pt 1",
            ],
            [
                "C1 metabolism",
                "Methanogenesis and methanotrophy",
                "acetate => methane, pt 2",
                "",
                "acetate kinase [EC:2.7.2.1] [RN:R00315]",
                "ack",
                "scaffold_1",
                False,
                "C1 metabolism: acetate => methane, pt 2",
            ],
            [
                "C1 metabolism",
                "Methanogenesis and methanotrophy",
                "acetate => methane, pt 3",
                "",
                "phosphate acetyltransferase [EC:2.3.1.8] [RN:R00230]",
                "",
                "scaffold_1",
                False,
                "C1 metabolism: acetate => methane, pt 3",
            ],
            [
                "C1 metabolism",
                "Methanogenesis and methanotrophy",
                "methanol => methane",
                "",
                "mtaB; 5-hydroxybenzimidazolylcobamide Co-methyltransferase",
                "mtaB",
                "scaffold_1",
                False,
                "C1 metabolism: methanol => methane",
            ],
            [
                "C1 metabolism",
                "Methanogenesis and methanotrophy",
                "trimethylamine => dimethylamine",
                "",
                "mttB; trimethylamine corrinoid protein Co-methyltransferase",
                "mttB",
                "scaffold_1",
                False,
                "C1 metabolism: trimethylamine => dimethylamine",
            ],
            [
                "C1 metabolism",
                "Methanogenesis and methanotrophy",
                "dimethylamine => monomethylamine",
                "",
                "mtbB; dimethylamine corrinoid protein Co-methyltransferase",
                "mtbB",
                "scaffold_1",
                False,
                "C1 metabolism: dimethylamine => monomethylamine",
            ],
            [
                "C1 metabolism",
                "Methanogenesis and methanotrophy",
                "monomethylamine => ammonia",
                "",
                "mtmB; methylamine corrinoid protein Co-methyltransferase",
                "mtmB",
                "scaffold_1",
                False,
                "C1 metabolism: monomethylamine => ammonia",
            ],
            [
                "C1 metabolism",
                "Methanogenesis and methanotrophy",
                "putative but not defining CO2 => methane",
                "",
                "formylmethanofuran dehydrogenase [EC:1.2.99.5] [RN:R03015]",
                "",
                "scaffold_1",
                False,
                "C1 metabolism: putative but not defining CO2 => methane",
            ],
            [
                "C1 metabolism",
                "Methanogenesis and methanotrophy",
                "methane => methanol, with oxygen (pmo)",
                "",
                "pmoA; Methane/ammonia monooxygenase subunit A (aka: Particulate methane monoxygenase, or subunit Beta) [EC:1.14.18.3] [RN:R09518]",
                "pmoA",
                "scaffold_1",
                False,
                "C1 metabolism: methane => methanol, with oxygen (pmo)",
            ],
            [
                "C1 metabolism",
                "Methanogenesis and methanotrophy",
                "methane => methanol, with oxygen (mmo)",
                "",
                "mmoX; Methane monooxygenase component A alpha chain (aka: Soluble methane monooxygenase, or methane hydroxylase) [EC1.14.13.25] [RN:R01142]",
                "",
                "scaffold_1",
                False,
                "C1 metabolism: methane => methanol, with oxygen (mmo)",
            ],
            [
                "CAZy",
                "CAZy",
                "Polyphenolics",
                "",
                "Polyphenolics Cleavage",
                "",
                "scaffold_1",
                False,
                "CAZy: Polyphenolics",
            ],
            [
                "CAZy",
                "CAZy",
                "Crystalline Cellulose",
                "",
                "Crystalline Cellulose Backbone Cleavage",
                "",
                "scaffold_1",
                False,
                "CAZy: Crystalline Cellulose",
            ],
            [
                "CAZy",
                "CAZy",
                "Amorphous Cellulose",
                "",
                "Amorphous Cellulose Backbone Cleavage; Amorphous Cellulose Oligo Cleavage",
                "",
                "scaffold_1",
                False,
                "CAZy: Amorphous Cellulose",
            ],
            [
                "CAZy",
                "CAZy",
                "Mucin",
                "",
                "Mucin Backbone Cleavage; Mucin Oligo Cleavage",
                "",
                "scaffold_1",
                False,
                "CAZy: Mucin",
            ],
            [
                "CAZy",
                "CAZy",
                "Sulf-Polysachharides",
                "",
                "Sulf-Polysachharides Backbone Cleavage; Sulf-Polysachharides Oligo Cleavage",
                "",
                "scaffold_1",
                False,
                "CAZy: Sulf-Polysachharides",
            ],
            [
                "CAZy",
                "CAZy",
                "Xyloglucan",
                "",
                "Xyloglucan Backbone Cleavage (Hemicellulose); Xyloglucan Oligo Cleavage (Hemicellulose)",
                "",
                "scaffold_1",
                False,
                "CAZy: Xyloglucan",
            ],
            [
                "CAZy",
                "CAZy",
                "Starch",
                "",
                "Starch Backbone Cleavage; Starch Oligo Cleavage",
                "",
                "scaffold_1",
                False,
                "CAZy: Starch",
            ],
            [
                "CAZy",
                "CAZy",
                "Chitin",
                "",
                "Chitin Backbone Cleavage; Chitin Oligo Cleavage",
                "",
                "scaffold_1",
                False,
                "CAZy: Chitin",
            ],
            [
                "CAZy",
                "CAZy",
                "Pectin",
                "",
                "Pectin Backbone Cleavage; Pectin Oligo Cleavage",
                "",
                "scaffold_1",
                False,
                "CAZy: Pectin",
            ],
            [
                "CAZy",
                "CAZy",
                "Alpha-galactans",
                "",
                "Alpha-galactans Backbone Cleavage; Alpha-galactans Oligo Cleavage",
                "",
                "scaffold_1",
                False,
                "CAZy: Alpha-galactans",
            ],
            [
                "CAZy",
                "CAZy",
                "Beta-galactan (pectic galactan)",
                "",
                "Beta-galactan (pectic galactan) Backbone Cleavage; Beta-galactan (pectic galactan) Oligo Cleavage",
                "",
                "scaffold_1",
                False,
                "CAZy: Beta-galactan (pectic galactan)",
            ],
            [
                "CAZy",
                "CAZy",
                "Mixed-Linkage glucans",
                "",
                "Mixed-Linkage glucans Backbone Cleavage (Hemicellulose); Mixed-Linkage glucans Oligo Cleavage (Hemicellulose)",
                "",
                "scaffold_1",
                False,
                "CAZy: Mixed-Linkage glucans",
            ],
            [
                "CAZy",
                "CAZy",
                "Xylans",
                "",
                "Xylan Backbone Cleavage (Hemicellulose); Xylan Oligo Cleavage (Hemicellulose)",
                "",
                "scaffold_1",
                False,
                "CAZy: Xylans",
            ],
            [
                "CAZy",
                "CAZy",
                "Beta-mannan",
                "",
                "Beta-mannan Backbone Cleavage (Hemicellulose); Beta-mannan Oligo Cleavage (Hemicellulose)",
                "",
                "scaffold_1",
                False,
                "CAZy: Beta-mannan",
            ],
            [
                "CAZy",
                "CAZy",
                "Alpha-mannan",
                "",
                "Alpha-mannan Backbone Cleavage (Hemicellulose); Alpha-mannan Oligo Cleavage (Hemicellulose)",
                "",
                "scaffold_1",
                False,
                "CAZy: Alpha-mannan",
            ],
            [
                "CAZy",
                "CAZy",
                "Arabinan",
                "",
                "Arabinan Backbone Cleavage; Arabinan Oligo Cleavage",
                "",
                "scaffold_1",
                False,
                "CAZy: Arabinan",
            ],
            [
                "CAZy",
                "CAZy",
                "Rhamnose cleavage",
                "",
                "Rhamnose Oligo cleavage",
                "",
                "scaffold_1",
                False,
                "CAZy: Rhamnose cleavage",
            ],
            [
                "CAZy",
                "CAZy",
                "Fucose Cleavage",
                "",
                "Fucose Oligo Cleavage",
                "",
                "scaffold_1",
                False,
                "CAZy: Fucose Cleavage",
            ],
            [
                "CAZy",
                "CAZy",
                "Arabinose cleavage",
                "",
                "Arabinose Oligo cleavage",
                "",
                "scaffold_1",
                False,
                "CAZy: Arabinose cleavage",
            ],
            [
                "SCFA/alcohol conversions",
                "SCFA and alcohol conversions",
                "pyruvate => acetyl CoA v1",
                "",
                "pyruvate dehydrogenase E1 component [EC:1.2.4.1]",
                "",
                "scaffold_1",
                False,
                "SCFA/alcohol conversions: pyruvate => acetyl CoA v1",
            ],
            [
                "SCFA/alcohol conversions",
                "SCFA and alcohol conversions",
                "pyruvate => acetyl CoA v2",
                "",
                "2-oxoglutarate/2-oxoacid ferredoxin oxidoreductase subunit alpha [EC:1.2.7.3, 1.2.7.11]",
                "",
                "scaffold_1",
                False,
                "SCFA/alcohol conversions: pyruvate => acetyl CoA v2",
            ],
            [
                "SCFA/alcohol conversions",
                "SCFA and alcohol conversions",
                "pyruvate => acetylCoA f+ formate v3",
                "",
                "formate C-acetyltransferase [EC:2.3.1.54]",
                "",
                "scaffold_1",
                False,
                "SCFA/alcohol conversions: pyruvate => acetylCoA f+ formate v3",
            ],
            [
                "SCFA/alcohol conversions",
                "SCFA and alcohol conversions",
                "acetate, pt 1",
                "",
                "phosphate acetyltransferase [EC:2.3.1.8] [RN:R00230], acetate kinase [EC:2.7.2.1] [RN:R00315]",
                "",
                "scaffold_1",
                False,
                "SCFA/alcohol conversions: acetate, pt 1",
            ],
            [
                "SCFA/alcohol conversions",
                "SCFA and alcohol conversions",
                "acetate, pt 2",
                "",
                "acetate---CoA ligase (ADP-forming) subunit alpha",
                "",
                "scaffold_1",
                False,
                "SCFA/alcohol conversions: acetate, pt 2",
            ],
            [
                "SCFA/alcohol conversions",
                "SCFA and alcohol conversions",
                "acetate, pt 3",
                "",
                "acetyl-CoA hydrolase [EC:3.1.2.1]",
                "",
                "scaffold_1",
                False,
                "SCFA/alcohol conversions: acetate, pt 3",
            ],
            [
                "SCFA/alcohol conversions",
                "SCFA and alcohol conversions",
                "lactate L",
                "",
                "L-lactate dehydrogenase [EC:1.1.1.27]; L-lactate dehydrogenase (cytochrome) [EC:1.1.2.3]",
                "",
                "scaffold_1",
                False,
                "SCFA/alcohol conversions: lactate L",
            ],
            [
                "SCFA/alcohol conversions",
                "SCFA and alcohol conversions",
                "lactate D",
                "",
                "D-lactate dehydrogenase [EC:1.1.1.28]; D-lactate dehydrogenase (quinone) [EC:1.1.5.12], D-lactate dehydrogenase (cytochrome) [EC:1.1.2.4], D-lactate dehydrogenase (cytochrome c-553)",
                "",
                "scaffold_1",
                False,
                "SCFA/alcohol conversions: lactate D",
            ],
            [
                "SCFA/alcohol conversions",
                "SCFA and alcohol conversions",
                "Butyrate, pt 1",
                "",
                "phosphate butyryltransferase [EC:2.3.1.19]",
                "",
                "scaffold_1",
                False,
                "SCFA/alcohol conversions: Butyrate, pt 1",
            ],
            [
                "SCFA/alcohol conversions",
                "SCFA and alcohol conversions",
                "Butyrate, pt 2",
                "",
                "butyrate kinase [EC:2.7.2.7], medium-chain acyl-CoA synthetase [EC:6.2.1.2]",
                "",
                "scaffold_1",
                False,
                "SCFA/alcohol conversions: Butyrate, pt 2",
            ],
            [
                "SCFA/alcohol conversions",
                "SCFA and alcohol conversions",
                "Propionate, pt 1",
                "",
                "propionate kinase [EC:2.7.2.15]",
                "",
                "scaffold_1",
                False,
                "SCFA/alcohol conversions: Propionate, pt 1",
            ],
            [
                "SCFA/alcohol conversions",
                "SCFA and alcohol conversions",
                "Propionate, pt 2",
                "",
                "propionate CoA-transferase [EC:2.8.3.1]",
                "",
                "scaffold_1",
                False,
                "SCFA/alcohol conversions: Propionate, pt 2",
            ],
            [
                "SCFA/alcohol conversions",
                "SCFA and alcohol conversions",
                "Alcohol production",
                "",
                "alcohol dehydrogenase [EC:1.1.1.1]",
                "",
                "scaffold_1",
                False,
                "SCFA/alcohol conversions: Alcohol production",
            ],
        ],
        columns=[
            "category",
            "subcategory",
            "function_name",
            "function_ids",
            "long_function_name",
            "gene_symbol",
            "genome",
            "present",
            "category_function_name",
        ],
    )


@pytest.fixture()
def test_annotation_path():
    return str(Path(__file__).parent.resolve() / "data/test_annotations.tsv")


@pytest.fixture()
def module_coverage_df_from_file():
    return pd.read_csv(Path(__file__).parent.resolve() / "data/module_coverage_df.tsv", sep="\t")


@pytest.fixture()
def etc_coverage_df_from_file():
    return pd.read_csv(Path(__file__).parent.resolve() / "data/etc_coverage_df.tsv", sep="\t")


@pytest.fixture()
def function_df_from_file():
    return pd.read_csv(Path(__file__).parent.resolve() / "data/function_df.tsv", sep="\t")


@pytest.fixture()
def taxonomy_tree():
    with open(Path(__file__).parent.resolve() / "data/taxonomy_tree.json") as f:
        d = json.load(f)
    return d
